AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS ParallelCluster on 2 availability zones

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Active Directory"
        Parameters: 
          - AdDomainName
          - AdDomainAddr
          - AdDomainReadOnlyUser
          - AdPasswordSecretArn
      - 
        Label: 
          default: "Amazon Elastic Filesystem"
        Parameters: 
          - EfsFilesystemId
      - 
        Label: 
          default: "Cluster"
        Parameters: 
          - OS
          - KeyName
          - HeadNodeSubnetId
      - 
        Label: 
          default: "Cluster:Compute Configuration"
        Parameters: 
          - ComputeSubnetIds
          - ComputeInstanceMax
      - 
        Label: 
          default: "Optional/Miscellaneous"
        Parameters: 
          - ParallelClusterVersion
          - SourceBucket
    ParameterLabels: 
      AdDomainName: 
        default: "Outputs/DomainName"
      AdDomainAddr: 
        default: "Outputs/DomainAddr"
      AdDomainReadOnlyUser: 
        default: "Outputs/DomainReadOnlyUser"
      AdPasswordSecretArn: 
        default: "Outputs/PasswordSecretArn"
      EfsFilesystemId:
        default: "Outputs/EfsFilesystemId"

Parameters:
  ParallelClusterVersion:
    Description: Version of AWS ParallelCluster to use
    Type: String
    Default: 3.6.0

  SourceBucket:
    Description: Bucket to pull recipe templates from
    Type: String
    Default: cfn3-dev-mwvaughn
    NoEcho: true

  # ClusterName:
  #   Description: Name of cluster. Note this must be different than the stack name.
  #   Type: String
  #   Default: tutorial

  ComputeInstanceMax:
    Description: Maximum number of compute instances in the queue
    Type: Number
    Default: 16

  KeyName:
    Description: EC2 SSH KeyPair to login to the head node
    Type: AWS::EC2::KeyPair::KeyName

  HeadNodeSubnetId:
    Description: Subnet ID where the head node will launch
    Type: AWS::EC2::Subnet::Id

  ComputeSubnetIds:
    Description: Subnet IDs where compute nodes will launch.
    Type: List<AWS::EC2::Subnet::Id>

  OS:
    Type: String
    Default: centos7
    AllowedValues:
      - alinux2
      - centos7
      - ubuntu1804
      - ubuntu2004
    Description: Enter alinux2, centos7, ubuntu1804 or ubuntu2004. Default is centos7.

  EfsFilesystemId:
    Description: ID for persistent EFS filesystem
    Type: String

  AdDomainName:
    Type: String
    Default: corp.pcluster.com

  AdDomainAddr:
    Type: String

  AdPasswordSecretArn:
    Type: String

  AdDomainReadOnlyUser:
    Type: String
    Default: cn=ReadOnlyUser,ou=Users,ou=CORP,dc=corp,dc=pcluster,dc=com

Resources:

  PclusterClusterProvider:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${AWS::Region}-aws-parallelcluster.s3.${AWS::Region}.${AWS::URLSuffix}/parallelcluster/${Version}/templates/custom_resource/cluster.yaml
        - { Version: !Ref ParallelClusterVersion }
      TimeoutInMinutes: 10

  # PclusterVpc:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     Parameters:
  #       CidrBlock: 10.3.0.0/16
  #       CidrPublicSubnetA: 10.3.128.0/20
  #       CidrPublicSubnetB: 10.3.144.0/20
  #       CidrPrivateSubnetA: 10.3.0.0/18
  #       CidrPrivateSubnetB: 10.3.64.0/18
  #     TemplateURL: !Sub
  #       - https://${Bucket}.s3.${Region}.amazonaws.com/main/recipes/net/hpc_networking_2az/assets/public-private.cfn.yml
  #       - { Bucket: !Ref SourceBucket, Region: !Ref AWS::Region }
  #     TimeoutInMinutes: 10

  PclusterCluster:
    Type: Custom::PclusterCluster
    Properties:
      ServiceToken: !GetAtt [ PclusterClusterProvider , Outputs.ServiceToken ]
      ClusterName: !Sub 'c-${AWS::StackName}'
      ClusterConfiguration:
        Image:
          Os: !Ref OS
        HeadNode:
          InstanceType: c5.24xlarge
          Networking:
            SubnetId: !Ref HeadNodeSubnetId
          Ssh:
            KeyName: !Ref KeyName
          Iam:
            AdditionalIamPolicies:
            - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          CustomActions:
            OnNodeConfigured:
              Script: https://raw.githubusercontent.com/spack/spack-configs/main/AWS/parallelcluster/postinstall.sh
        Scheduling:
          Scheduler: slurm
          SlurmSettings:
            ScaledownIdletime: 120
          SlurmQueues:
          - Name: normal
            CustomSlurmSettings:
              MaxTime: "24:00:00"
            ComputeResources:
            - Name: cr1
              Instances:
                - InstanceType: c5.24xlarge
                - InstanceType: m5.24xlarge
                - InstanceType: r5.24xlarge
              MinCount: 0
              MaxCount: !Ref ComputeInstanceMax
            Networking:
              SubnetIds: !Ref ComputeSubnetIds
          - Name: gpu
            CustomSlurmSettings:
              MaxTime: "24:00:00"
            ComputeResources:
            - Name: gr1
              Instances:
              - InstanceType: g5.4xlarge
              MinCount: 0
              MaxCount: !Ref ComputeInstanceMax
            Networking:
              SubnetIds: !Ref ComputeSubnetIds
        SharedStorage:
          - Name: Efs0
            StorageType: Efs
            MountDir: /shared/efs/apps
          - Name: Efs1
            StorageType: Efs
            MountDir: /shared/efs/data
            EfsSettings:
              FileSystemId: !Ref EfsFilesystemId
        DirectoryService:
          DomainName: !Ref AdDomainName
          DomainAddr: !Ref AdDomainAddr
          PasswordSecretArn: !Ref AdPasswordSecretArn
          DomainReadOnlyUser: !Ref AdDomainReadOnlyUser
          GenerateSshKeysForUsers: true
          AdditionalSssdConfigs:
            ldap_auth_disable_tls_never_use_in_production: True
            cache_credentials: false
            override_homedir: /shared/efs/data/home/%u

Outputs:
  HeadNodeIp:
    Description: The Public IP address of the HeadNode
    Value: !GetAtt [ PclusterCluster, headNode.publicIpAddress ]
  ValidationMessages:
    Description: Any warnings from cluster create or update operations.
    Value: !GetAtt PclusterCluster.validationMessages

# TODO: include cluster name in override_homedir to allow for multiple clusters on same EFS
